# Form implementation generated from reading ui file 'bandau.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.link = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.link.setGeometry(QtCore.QRect(40, 140, 731, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.link.setFont(font)
        self.link.setText("")
        self.link.setObjectName("link")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start.setGeometry(QtCore.QRect(40, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.atsakymas = QtWidgets.QLabel(parent=self.centralwidget)
        self.atsakymas.setGeometry(QtCore.QRect(40, 240, 721, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.atsakymas.setFont(font)
        self.atsakymas.setObjectName("atsakymas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Įveskite puslapio adresas iš svetainės elenta.lt"))
        self.start.setText(_translate("MainWindow", "Pateikti"))
        self.atsakymas.setText(_translate("MainWindow", ""))
